server:
  port: 8101

spring:
  application:
    name: msvc-sale
  datasource:
    driver-class-name: org.postgresql.Driver
    #url: jdbc:postgresql://25.1.49.168:5432/sale
    #username: postgres
    #password: 12345
    url: jdbc:postgresql://localhost:5432/sale
    username: postgres
    password: "#Mahecha3." # Ajusta la contraseña según corresponda
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defautlZone: http://localhost:8761/eureka