server:
  port: 8100

spring:
  application:
    name: msvc-customer
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://34.123.35.169:5432/customer
    username: postgres
    password: AnaGourmet.$!
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka