server:
  port: 8101

spring:
  application:
    name: msvc-sale
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://34.123.35.169:5432/sale
    username: postgres
    password: AnaGourmet.$!
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defautlZone: http://localhost:8761/eureka