spring:
  application:
    name: msvc-inventory
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect